{% set name = "ritas" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ritas-{{ version }}.tar.gz
  sha256: 2bb70aef9e7ea27388a44e9a762f854965bd1b7e4bb7b9cb0a777b6c9a6e9a12

build:
  entry_points:
    - ritas = ritas.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - click
    - geopandas
    - matplotlib-base
    - pandas
    - pyarrow
    - pykrige
    - pyproj
    - shapely
    - streamlit
    - tqdm

test:
  imports:
    - ritas
  commands:
    - pip check
    - ritas --help
  requires:
    - pip

about:
  home: https://github.com/jarad/pyritas
  license: MIT
  license_file: LICENSE
  summary: |
    RITAS is a package to spatially and statistically process agricultural
    yield monitor data.

extra:
  recipe-maintainers:
    - akrherz
